var data_home_page = {
    JOB_LIST: [
        {
            company_name: "The coffee house",
            image_link: "https://rubee.com.vn/admin/webroot/upload/image/images/tin-tuc/the-coffee-house-logo-2.jpg",
            title: "Nhân viên cửa hàng",
            job_type: "Phục vụ",
            tag_list: [],
            id_job: 0,
            type: "Bán thời gian",
            salary: "3,000,000",
            company_address: "quận Tân Bình, thành phố Hồ Chí Minh",
            description: ["• Phục vụ khách hàng.",
                "• Đảm bảo vệ sinh cửa hàng làm việc.",
                "• Hỗ trợ các công việc trong quầy và sảnh theo sự sắp xếp của Quản lý cửa hàng."],
            require: ["• Các bạn học sinh, sinh viên đủ 18 tuổi trở lên có khả năng làm từ 24h/ tuần trở lên (tương đương 4-5 ca làm việc/ tuần, mỗi ca 5-6 tiếng).",
                "• Đam mê & muốn tích lũy kinh nghiệm làm việc trong ngành dịch vụ F&B ở các mảng (phục vụ khách hàng, pha chế)",
                "• Sức khỏe tốt, siêng năng, chủ động trong công việc."],
            benefit: ["• Làm việc trong môi trường dịch vụ chuyên nghiệp.", "• Được học hỏi, đào tạo và phát triển kỹ năng pha chế & thu ngân (nếu muốn).",
                "• Cơ hội thăng tiến nhanh lên các vị trí quản lý với các cửa hàng mới mở hằng tuần.", "• Các chương trình ưu đãi dành cho nhân viên TCH."],
            date_create: "10/06/2021",
            duration: "10/08/2021",
            status: true,
            email: "hi@thecoffeehouse.vn",
            phone: "02871078079",
            address: "88 Cao Thắng, Phường 4, Quận 3, Tp.HCM"

        }, {
            company_name: "The coffee house",
            image_link: "https://rubee.com.vn/admin/webroot/upload/image/images/tin-tuc/the-coffee-house-logo-2.jpg",
            title: "Nhân viên cửa hàng",
            job_type: "Phục vụ",
            tag_list: [],
            id_job: 1,
            type: "Toàn thời gian",
            salary: "7,000,000",
            company_address: "Quận 1, thành phố Hồ Chí Minh",
            description: ["• Phục vụ khách hàng.",
                "• Đảm bảo vệ sinh cửa hàng làm việc.",
                "• Hỗ trợ các công việc trong quầy và sảnh theo sự sắp xếp của Quản lý cửa hàng."],
            require: ["• Các bạn học sinh, sinh viên đủ 18 tuổi trở lên có khả năng làm từ 24h/ tuần trở lên (tương đương 4-5 ca làm việc/ tuần, mỗi ca 5-6 tiếng).",
                "• Đam mê & muốn tích lũy kinh nghiệm làm việc trong ngành dịch vụ F&B ở các mảng (phục vụ khách hàng, pha chế)",
                "• Sức khỏe tốt, siêng năng, chủ động trong công việc."],
            benefit: ["• Làm việc trong môi trường dịch vụ chuyên nghiệp.", "• Được học hỏi, đào tạo và phát triển kỹ năng pha chế & thu ngân (nếu muốn).",
                "• Cơ hội thăng tiến nhanh lên các vị trí quản lý với các cửa hàng mới mở hằng tuần.", "• Các chương trình ưu đãi dành cho nhân viên TCH."],
            date_create: "10/06/2021",
            duration: "10/08/2021",
            status: true,
            email: "hi@thecoffeehouse.vn",
            phone: "02871078079",
            address: "88 Cao Thắng, Phường 4, Quận 3, Tp.HCM"

        }, {
            company_name: "CÔNG TY CP HÀNG TIÊU DÙNG MASAN",
            image_link: "https://cdn.brvn.vn/news/480px/2013/masanhuydongvon0_1373616909.jpg",
            title: "Nhân Viên Bán Hàng",
            job_type: "Bán hàng",
            tag_list: [],
            id_job: 2,
            type: "Bán thời gian",
            salary: "3,000,000",
            company_address: " MPlaza, 39 Lê Duẩn, Bến Nghé, Quận 1, Hồ Chí Minh",
            description: ["• Thực hiện chia chọn hàng hóa theo hướng dẫn",
                "• Chịu KPI bán hàng theo target mỗi ngày",
                "• Nhiệt tình, vui vẻ, không ngại việc"],
            require: ["• Các bạn học sinh, sinh viên đủ 18 tuổi trở lên có khả năng làm từ 24h/ tuần trở lên (tương đương 4-5 ca làm việc/ tuần, mỗi ca 5-6 tiếng).",
                "• Nhanh nhẹn, hoạt bát, siêng năng, tính tình trung thực, nắm bắt vấn đề nhanh, có tố chất sales",
                "• Sức khỏe tốt, siêng năng, chủ động trong công việc."],
            benefit: ["• Chế độ phúc lợi tốt, được thưởng lễ tết.", "• Được đào tạo nâng cao nghiệp vụ trong quá trình làm việc.",
                "• Được làm việc trong môi trường chuyên nghiệp, năng động và hiệu quả.", "• Có cơ hội thăng tiến cao trong công việc."],
            date_create: "01/06/2021",
            duration: "01/08/2021",
            status: true,
            email: "info@masan.com.vn",
            phone: "19007911",
            address: "MPlaza, 39 Lê Duẩn, Bến Nghé, Quận 1, Hồ Chí Minh"

        }, {
            company_name: "Công Ty Tnhh A.N Sài Gòn Group",
            image_link: "https://cdn1.timviecnhanh.com/images/default/2021/06/18/images/162400169835.jpeg",
            title: "Thu Ngân",
            job_type: "Bán hàng",
            tag_list: [],
            id_job: 3,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Số 85 Đường Số 6, Ấp Tiền Lân, Xã Bà Điểm, Huyện Hóc Môn, Thành phố Hồ Chí Minh",
            description: ["• Tính tiền cho khách",
                "• Kiểm tra hóa đơn, chứng từ cuối ngày",
                "• Hỗ trợ bán đồ ăn chín tại quầy"],
            require: ["• Các bạn học sinh, sinh viên đủ 18 tuổi trở lên có khả năng làm từ 24h/ tuần trở lên (tương đương 4-5 ca làm việc/ tuần, mỗi ca 5-6 tiếng).",
                "• Nhanh nhẹn, hoạt bát, siêng năng, tính tình trung thực, nắm bắt vấn đề nhanh",
                "• Sức khỏe tốt, siêng năng, chủ động trong công việc."],
            benefit: ["• Chế độ phúc lợi tốt, được thưởng lễ tết.", "• Được đào tạo nâng cao nghiệp vụ trong quá trình làm việc.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người.", "• Có cơ hội thăng tiến cao trong công việc."],
            date_create: "18/06/2021",
            duration: "18/08/2021",
            status: true,
            email: "about@saigoncoop.com.vn",
            phone: "19006564",
            address: "Số 85 Đường Số 6, Ấp Tiền Lân, Xã Bà Điểm, Huyện Hóc Môn, Thành phố Hồ Chí Minh"

        }, {
            company_name: "CÔNG TY CP PIZZA NGON",
            image_link: "https://cdn1.timviecnhanh.com/asset/home/img/employer/5aa88868f0846_1520994408.png",
            title: "Nhân Viên Call Center",
            job_type: "Call Teller",
            tag_list: [],
            id_job: 4,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Tòa nhà Lottery Tower - Lầu 10, 77 Trần Nhân Tôn, Phường 9, Quận 5, HCM",
            description: ["• Làm việc tại 105-107 Nguyễn Thái Học, P. Cầu Ông Lãnh, Q.1, TP.HCM",
                "• Làm việc part-time theo ca: 4-6 giờ/ca",
                "• Tiếp nhận order của khách hàng",
                "• Giải đáp và tư vấn về sản phẩm và các chương trình khuyến mãi",
                "• Giải quyết các phản hồi, yêu cầu, khiếu nại của khách hàng"],
            require: ["• Có thể làm việc xoay ca linh động (bắt buộc phải làm việc vào thứ 3, thứ 7 và Chủ nhật), có thể làm việc các ngày Lễ, Tết.",
                "• Giọng nói dễ nghe (không ngọng)",
                "• Chịu được áp lực cao về cuộc gọi"],
            benefit: ["• Hưởng lương gấp 3 lần khi làm việc vào Lễ, Tết", "• Được đào tạo nâng cao nghiệp vụ trong quá trình làm việc.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người.", "• Có cơ hội thăng tiến cao trong công việc."],
            date_create: "19/06/2021",
            duration: "19/08/2021",
            status: true,
            email: "pizza.ngon@gmail.com",
            phone: "19007272",
            address: "Tòa nhà Lottery Tower - Lầu 10, 77 Trần Nhân Tôn, Phường 9, Quận 5, HCM"

        }, {
            company_name: "CÔNG TY CP PIZZA NGON",
            image_link: "https://cdn1.timviecnhanh.com/asset/home/img/employer/5aa88868f0846_1520994408.png",
            title: "Nhân Viên Part Time",
            job_type: "Bán hàng",
            tag_list: [],
            id_job: 5,
            type: "Bán thời gian",
            salary: "3,000,000",
            company_address: "Tòa nhà Lottery Tower - Lầu 10, 77 Trần Nhân Tôn, Phường 9, Quận 5, HCM",
            description: ["• Tính tiền cho khách",
                "• Kiểm tra hóa đơn, chứng từ cuối ngày",
                "• Hỗ trợ bán đồ ăn chín tại quầy"],
            require: ["• Các bạn học sinh, sinh viên đủ 18 tuổi trở lên có khả năng làm từ 24h/ tuần trở lên (tương đương 4-5 ca làm việc/ tuần, mỗi ca 5-6 tiếng).",
                "• Nhanh nhẹn, hoạt bát, siêng năng, tính tình trung thực, nắm bắt vấn đề nhanh",
                "• Sức khỏe tốt, siêng năng, chủ động trong công việc."],
            benefit: ["• Chế độ phúc lợi tốt, được thưởng lễ tết.", "• Được đào tạo nâng cao nghiệp vụ trong quá trình làm việc.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người.", "• Có cơ hội thăng tiến cao trong công việc."],
            date_create: "19/06/2021",
            duration: "19/08/2021",
            status: true,
            email: "pizza.ngon@gmail.com",
            phone: "19007272",
            address: "Tòa nhà Lottery Tower - Lầu 10, 77 Trần Nhân Tôn, Phường 9, Quận 5, HCM"

        }, {
            company_name: "TT Trực Tuyến Workonline 24H",
            image_link: "https://cdn1.timviecnhanh.com/asset/home/img/employer/5ebcabed03b02_1589423085.jpg",
            title: "Nhân Viên Nhập Dữ Liệu",
            job_type: "",
            tag_list: [],
            id_job: 6,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Quận 3, thành phố Hồ Chí Minh",
            description: ["• Công việc chọn giải quyết dử liệu hình ảnh từ phần mềm đưa xuống, làm trên máy vi tính hoặc điện thoại của bạn, không ràng buộc thời gian rảnh lúc nào thì làm, có thể làm tại nhà hoặc bất cử đâu có internet kết nối với máy vi tính hoặc điện thoại. Đăng ký làm việc kiếm tiền trên website: httpS://www.woh247.comg"],
            require: ["• Có kiếm thức cơ bản về sử dụng internet, có máy vi tinh hoặc điện thoại..",
                "•Có tốc độ đánh máy nhanh và chút vốn tiếng anh là một lợi thế.",
                "• Kiên trì xiệng năng trong công việc."],
            benefit: ["• Làm lâu dài sẽ được ưu tiên tăng % tiền thưởng.", "• Lương theo sản lượng.",
                "• Giờ giấc tự do, chủ động được thời gian làm việc."],
            date_create: "19/06/2021",
            duration: "19/08/2021",
            status: true,
            email: "trinhtran.manager@gmail.com",
            phone: "0127898264",
            address: "Quận 3, thành phố Hồ Chí Minh"

        }, {
            company_name: "Công Ty Tnhh Ministop Việt Nam",
            image_link: "https://cdn1.timviecnhanh.com/images/default/2021/06/18/images/162400169835.jpeg",
            title: "Nhân Viên Bán Hàng",
            job_type: "Bán hàng",
            tag_list: [],
            id_job: 7,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Số 85 Đường Số 6, Ấp Tiền Lân, Xã Bà Điểm, Huyện Hóc Môn, Thành phố Hồ Chí Minh",
            description: ["• NV quầy bán hàng, thanh toán tính tiền.",
                "• NV quầy giữ đồ, chăm sóc khách hàng.",
                "• NV kiểm kê hàng hóa và hóa đơn hàng.",
                "• MiniStop : Q.1, Q.2 , Q.3, Q.4, Q.5, Q.6, Q.7, Q.8.Q.9, Q.10, Q.11, Phú nhuận. Bình Thạnh.Tân bình, Tân phú"],
            require: ["• Các bạn học sinh, sinh viên đủ 18 tuổi trở lên có khả năng làm từ 24h/ tuần trở lên (tương đương 4-5 ca làm việc/ tuần, mỗi ca 5-6 tiếng).",
                "• Nhanh nhẹn, hoạt bát, siêng năng, tính tình trung thực, nắm bắt vấn đề nhanh",
                "• Sức khỏe tốt, siêng năng, chủ động trong công việc."],
            benefit: ["• Chế độ phúc lợi tốt, được thưởng lễ tết.", "• Được đào tạo nâng cao nghiệp vụ trong quá trình làm việc.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người.", "• Có cơ hội thăng tiến cao trong công việc."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: true,
            email: "hi@ministop.com",
            phone: "19004546",
            address: "Số 85 Đường Số 6, Ấp Tiền Lân, Xã Bà Điểm, Huyện Hóc Môn, Thành phố Hồ Chí Minh"

        }, {
            company_name: "Siêu Thị Big C",
            image_link: "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/18158268c55b328c797f859b5fc9add6.png",
            title: "Nhân viên siêu thị",
            job_type: "",
            tag_list: [],
            id_job: 8,
            type: "Bán thời gian",
            salary: "3,000,000",
            company_address: "Hồ Chí Minh, Thành phố Hồ Chí Minh",
            description: ["• NV trực phòng camera.",
                "• NV quầy bán hàng, chăm sóc khách hàng.",
                "• NV quầy rượu, nước hoa, mỹ phẩm, trang sức...",
                "• NV kho, kiểm kê, xuất nhập hàng hóa."],
            require: ["• Các bạn học sinh, sinh viên đủ 18 tuổi trở lên có khả năng làm từ 24h/ tuần trở lên (tương đương 4-5 ca làm việc/ tuần, mỗi ca 5-6 tiếng).",
                "• Nhanh nhẹn, hoạt bát, siêng năng, tính tình trung thực, nắm bắt vấn đề nhanh",
                "• Sức khỏe tốt, siêng năng, chủ động trong công việc."],
            benefit: ["• Chế độ phúc lợi tốt, được thưởng lễ tết.", "• Được đào tạo nâng cao nghiệp vụ trong quá trình làm việc.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người.", "• Có cơ hội thăng tiến cao trong công việc."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: true,
            email: "info@bigc.com",
            phone: "19001864",
            address: "Hồ Chí Minh, Thành phố Hồ Chí Minh"

        }, {
            company_name: "Digiworld Corporation",
            image_link: "https://media-exp1.licdn.com/dms/image/C4E0BAQFeF_eL00Sg3w/company-logo_200_200/0/1519899505547?e=2159024400&v=beta&t=79aGnfAl0HDtz0ZbWd7G9i_cNlyYo0Oc4zjBp_MQDgY",
            title: "Thực tập sinh Tuyển dụng",
            job_type: "Service",
            tag_list: [],
            id_job: 9,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "231 - 233 Lê Thánh Tôn, Quận 1, thành phố Hồ Chí Minh",
            description: ["• Hỗ trợ công tác truyền thông, tìm kiếm ứng viên theo yêu cầu của công ty.",
                "• Hỗ trợ công tác tuyển chọn (cập nhật hồ sơ ứng viên, set-up phỏng vấn, tiếp đón ứng viên, tham gia phỏng vấn trực tiếp, thông báo kết quả phỏng vấn...).",
                "• Tiếp nhận và xử lý hồ sơ Nhân viên mới",
                "• Lập kế hoạch làm việc, báo cáo kết quả công việc định kỳ lên quản lý trực tiếp."],
            require: ["• Các bạn học sinh, sinh viên đủ 18 tuổi trở lên có khả năng làm từ 24h/ tuần trở lên (tương đương 4-5 ca làm việc/ tuần, mỗi ca 5-6 tiếng).",
                "• Nhanh nhẹn, hoạt bát, siêng năng, tính tình trung thực, nắm bắt vấn đề nhanh",
                "• Sức khỏe tốt, siêng năng, chủ động trong công việc."],
            benefit: ["• Chế độ phúc lợi tốt, được thưởng lễ tết.", "• Được đào tạo nâng cao nghiệp vụ trong quá trình làm việc.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người.", "• Có cơ hội thăng tiến cao trong công việc."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: true,
            email: "digiworld.corp@digiworld.com.vn",
            phone: "19003110",
            address: "231 - 233 Lê Thánh Tôn, Quận 1, thành phố Hồ Chí Minh"

        }, {
            company_name: "Cafe tại Hồ Chí Minh",
            image_link: "",
            title: "Nhân viên phục vụ",
            job_type: "Nhân viên cửa hàng",
            tag_list: [],
            id_job: 10,
            type: "Bán thời gian",
            salary: "2,500,000",
            company_address: "Quận 4, thành phố Hồ Chí Minh",
            description: ["• Quán cafe mình quán nhỏ nên cần 1 bạn nữ chịu khó muốn làm thêm.",
                "• Nhiệm vụ chỉ phục vụ với rửa ly.",
                "• Làm từ 17h30 tới 22h30(5 tiếng)"],
            require: ["• Các bạn học sinh, sinh viên đủ 18 tuổi trở lên có khả năng làm từ 24h/ tuần trở lên (tương đương 4-5 ca làm việc/ tuần, mỗi ca 5-6 tiếng).",
                "• Nhanh nhẹn, hoạt bát, siêng năng, tính tình trung thực, nắm bắt vấn đề nhanh",
                "• Sức khỏe tốt, siêng năng, chủ động trong công việc."],
            benefit: ["• Chế độ phúc lợi tốt, được thưởng lễ tết.", "• Được đào tạo nâng cao nghiệp vụ trong quá trình làm việc.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người.", "• Có cơ hội thăng tiến cao trong công việc."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: true,
            email: "antran1212@gmail.com",
            phone: "0962888475",
            address: "Quận 4, thành phố Hồ Chí Minh"

        }, {
            company_name: "Tpbank",
            image_link: "https://monfin.vn/images/source/thebank_tpbank_1539081891.jpg",
            title: "Nhân viên ngân hàng",
            job_type: "Nhân viên",
            tag_list: [],
            id_job: 11,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Hồ Chí Minh, Thành phố Hồ Chí Minh",
            description: ["• Ưu tiên sinh viên đang học hoặc mới ra trường tại các trường khu vực HCM, Chuyên ngành tài chính ngân hàng..",
                "• Chủ động, nhanh nhẹn trong việc học hỏi.",
                "• Các bạn học trái ngành có mong muốn làm việc lâu dài trong ngân hàng, đam mê kím tiền."],
            require: ["• Các bạn học sinh, sinh viên đủ 18 tuổi trở lên có khả năng làm từ 24h/ tuần trở lên (tương đương 4-5 ca làm việc/ tuần, mỗi ca 5-6 tiếng).",
                "• Nhanh nhẹn, hoạt bát, siêng năng, tính tình trung thực, nắm bắt vấn đề nhanh",
                "• Sức khỏe tốt, siêng năng, chủ động trong công việc."],
            benefit: ["• Lương cứng + kèm bonus ( trở thành nhân viên chính thức sẽ được hưởng tất cả quyền lợi từ ngân hàng).", "• Được đào tạo nâng cao nghiệp vụ trong quá trình làm việc.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người.", "• Có cơ hội thăng tiến cao trong công việc."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: true,
            email: "tpbank.info@tpbank.com",
            phone: "1900585885",
            address: "160 Bùi Thị Xuân, Phường Phạm Ngũ Lão, Quận 1, Tp.HCM"

        }, {
            company_name: "Đại lý tại quận 4",
            image_link: "",
            title: "Nhân viên bán hàng",
            job_type: "Nhân viên bán hàng",
            tag_list: [],
            id_job: 12,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Quận 4, Hồ Chí Minh, Thành phố Hồ Chí Minh",
            description: ["• Chủ động, nhanh nhẹn trong việc học hỏi."],
            require: ["• Tuổi từ 18 ~ 30 tuổi, tốt nghiệp THPT.",
                "• Ứng sử tốt"],
            benefit: ["• Lương cứng + kèm bonus.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: true,
            email: "antran1212@gmail.com",
            phone: "0962888475",
            address: "Quận 4, thành phố Hồ Chí Minh"

        }, {
            company_name: "Đại lý bán bột Yến Mạch quận",
            image_link: "",
            title: "Nhân viên bán hàng",
            job_type: "Nhân viên bán hàng",
            tag_list: [],
            id_job: 13,
            type: "Bán thời gian",
            salary: "3,000,000",
            company_address: "Quận Gò Vấp, Hồ Chí Minh, Thành phố Hồ Chí Minh",
            description: ["• Cần 3 bạn bán bột yết mạch mattcha,.... tại khu vực quận Gò Vấp",
                "• Chủ động, nhanh nhẹn trong việc học hỏi."],
            require: ["• Tuổi từ 18 ~ 30 tuổi, tốt nghiệp THPT.",
                "• Ứng sử tốt"],
            benefit: ["• Lương cứng + kèm bonus.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: true,
            email: "antran1212@gmail.com",
            phone: "0962888475",
            address: "Quận Gò Vấp, Hồ Chí Minh, Thành phố Hồ Chí Minh"

        }, {
            company_name: "Công ty TNHH Vòng Tròn Đỏ",
            image_link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBtmE5u0HTHkD8cmS9ilCnQ8YgkZDHG7gfLItW_I7LcJ2ImtwMZoAKnyMwTkp4oA16-hE&usqp=CAU",
            title: "Nhân viên bán hàng",
            job_type: "Nhân viên bán hàng",
            tag_list: [],
            id_job: 14,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Quận Gò Vấp, Hồ Chí Minh, Thành phố Hồ Chí Minh",
            description: ["• Chào hỏi và phục vụ khách hàng thân thiện, nhanh nhẹn, nhiệt tình",
                "• Chủ động, nhanh nhẹn trong việc học hỏi.",
                "• Tính tiền và giới thiệu sản phẩm, chương trình khuyến mãi cho khách hàng",
                "• Vệ sinh hàng hóa, quầy kệ, khu vực làm việc tại cửa hàng"],
            require: ["• Tuổi từ 18 ~ 30 tuổi, tốt nghiệp THPT.",
                "• Ứng sử tốt"],
            benefit: ["• Lương cứng + kèm bonus.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: true,
            email: "info@circlek.com.vn",
            phone: "19003110",
            address: "160 Bùi Thị Xuân, Phường Phạm Ngũ Lão, Quận 1, Tp.HCM"

        }, {
            company_name: "Công ty TNHH Vòng Tròn Đỏ",
            image_link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBtmE5u0HTHkD8cmS9ilCnQ8YgkZDHG7gfLItW_I7LcJ2ImtwMZoAKnyMwTkp4oA16-hE&usqp=CAU",
            title: "Nhân viên bán hàng",
            job_type: "Nhân viên bán hàng",
            tag_list: [],
            id_job: 15,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Quận 7, Hồ Chí Minh, Thành phố Hồ Chí Minh",
            description: ["• Chào hỏi và phục vụ khách hàng thân thiện, nhanh nhẹn, nhiệt tình",
                "• Chủ động, nhanh nhẹn trong việc học hỏi.",
                "• Tính tiền và giới thiệu sản phẩm, chương trình khuyến mãi cho khách hàng",
                "• Vệ sinh hàng hóa, quầy kệ, khu vực làm việc tại cửa hàng"],
            require: ["• Tuổi từ 18 ~ 30 tuổi, tốt nghiệp THPT.",
                "• Ứng sử tốt"],
            benefit: ["• Lương cứng + kèm bonus.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: true,
            email: "info@circlek.com.vn",
            phone: "19003110",
            address: "160 Bùi Thị Xuân, Phường Phạm Ngũ Lão, Quận 1, Tp.HCM"

        }, {
            company_name: "Công ty TNHH Vòng Tròn Đỏ",
            image_link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBtmE5u0HTHkD8cmS9ilCnQ8YgkZDHG7gfLItW_I7LcJ2ImtwMZoAKnyMwTkp4oA16-hE&usqp=CAU",
            title: "Nhân viên bán hàng",
            job_type: "Nhân viên bán hàng",
            tag_list: [],
            id_job: 15,
            type: "Toàn thời gian",
            salary: "5,000,000",
            company_address: "Quận 7, Hồ Chí Minh, Thành phố Hồ Chí Minh",
            description: ["• Chào hỏi và phục vụ khách hàng thân thiện, nhanh nhẹn, nhiệt tình",
                "• Chủ động, nhanh nhẹn trong việc học hỏi.",
                "• Tính tiền và giới thiệu sản phẩm, chương trình khuyến mãi cho khách hàng",
                "• Vệ sinh hàng hóa, quầy kệ, khu vực làm việc tại cửa hàng"],
            require: ["• Tuổi từ 18 ~ 30 tuổi, tốt nghiệp THPT.",
                "• Ứng sử tốt"],
            benefit: ["• Lương cứng + kèm bonus.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: true,
            email: "info@circlek.com.vn",
            phone: "19003110",
            address: "160 Bùi Thị Xuân, Phường Phạm Ngũ Lão, Quận 1, Tp.HCM"

        }, {
            company_name: "Công ty TNHH Vòng Tròn Đỏ",
            image_link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBtmE5u0HTHkD8cmS9ilCnQ8YgkZDHG7gfLItW_I7LcJ2ImtwMZoAKnyMwTkp4oA16-hE&usqp=CAU",
            title: "Nhân viên bán hàng",
            job_type: "Nhân viên bán hàng",
            tag_list: [],
            id_job: 16,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Quận Bình Thạnh, Hồ Chí Minh, Thành phố Hồ Chí Minh",
            description: ["• Chào hỏi và phục vụ khách hàng thân thiện, nhanh nhẹn, nhiệt tình",
                "• Chủ động, nhanh nhẹn trong việc học hỏi.",
                "• Tính tiền và giới thiệu sản phẩm, chương trình khuyến mãi cho khách hàng",
                "• Vệ sinh hàng hóa, quầy kệ, khu vực làm việc tại cửa hàng"],
            require: ["• Tuổi từ 18 ~ 30 tuổi, tốt nghiệp THPT.",
                "• Ứng sử tốt"],
            benefit: ["• Lương cứng + kèm bonus.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: true,
            email: "info@circlek.com.vn",
            phone: "19003110",
            address: "160 Bùi Thị Xuân, Phường Phạm Ngũ Lão, Quận 1, Tp.HCM"

        }, {
            company_name: "Công ty TNHH Vòng Tròn Đỏ",
            image_link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBtmE5u0HTHkD8cmS9ilCnQ8YgkZDHG7gfLItW_I7LcJ2ImtwMZoAKnyMwTkp4oA16-hE&usqp=CAU",
            title: "Nhân viên bảo vệ",
            job_type: "Nhân viên bảo vệ",
            tag_list: [],
            id_job: 17,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Quận Gò Vấp, Hồ Chí Minh, Thành phố Hồ Chí Minh",
            description: ["• Chào hỏi và phục vụ khách hàng thân thiện, nhanh nhẹn, nhiệt tình",
                "• Chủ động, nhanh nhẹn trong việc học hỏi."],
            require: ["• Tuổi từ 18 ~ 30 tuổi, tốt nghiệp THPT.",
                "• Ứng sử tốt"],
            benefit: ["• Lương cứng + kèm bonus.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: true,
            email: "info@circlek.com.vn",
            phone: "19003110",
            address: "160 Bùi Thị Xuân, Phường Phạm Ngũ Lão, Quận 1, Tp.HCM"

        }, {
            company_name: "Công ty cổ phần Beemart",
            image_link: "https://tea-3.lozi.vn/v1/images/resized/beemart-1531826021-1-6102678-1531891148?w=640&type=s",
            title: "Thực tập sinh",
            job_type: "Nhân viên",
            tag_list: [],
            id_job: 18,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Quận Gò Vấp, Hồ Chí Minh, Thành phố Hồ Chí Minh",
            description: ["• Sinh viên Đại học năm 2 đến năm cuối hoặc mới ra trường",
                "• Chủ động, nhanh nhẹn trong việc học hỏi.",
                "• Part-time 4h/ ngày , tối thiểu 24h/ tuần . Dự kiến chương trình thực tập trong 3 tháng.",
                "• Quản lý hàng hóa, Support hàng hóa cho các điểm cửa hàng"],
            require: ["• Là sinh viên các trường Đại học từ năm 3 trở đi hoặc mới ra trường, Ưu tiên các sinh viên đang theo học đúng chuyên ngành thực tập..",
                "• Ham học hỏi, Tư duy tốt, Tinh thần sẵn sàng và không ngại rèn luyện bản thân trong môi trường có áp lực công việc để lớn!",
                "• Có niềm yêu thích và kiến thức về Các loại Bánh là một điểm cộng."],
            benefit: ["• Lương cứng + kèm bonus.",
                "• Cơ hội trải nghiệm thực tế, thực chiến chuyên môn, học tập và làm việc trong môi trường nhiều nhân sự trẻ, năng động. Tham gia vào các hoạt động sinh hoạt đoàn thể...."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: true,
            email: "beemart@gmail.com",
            phone: "19001115",
            address: "Quận Gò Vấp, Hồ Chí Minh, Thành phố Hồ Chí Minh"

        }, {
            company_name: "Công ty ECPay",
            image_link: "https://haymora.com/upload/images/cong_nghe_thong_tin/phan_mem/ecpay/ecpay.jpg",
            title: "Thực tập sinh Tuyển dụng",
            job_type: "Nhân viên",
            tag_list: [],
            id_job: 19,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Quận Gò Vấp, Hồ Chí Minh, Thành phố Hồ Chí Minh",
            description: ["• Thực hiện các công tác đăng tuyển, sàng lọc, setup phỏng vấn",
                "• Tham gia công tác phỏng vấn.",
                "• Các thủ tục thư mời làm việc và tiếp nhận nhân sự mới.",
                "• Thực hiện các công tác khác nếu có"],
            require: ["• Là sinh viên các trường Đại học từ năm 3 trở đi hoặc mới ra trường, Ưu tiên các sinh viên đang theo học đúng chuyên ngành thực tập..",
                "• Ham học hỏi, Tư duy tốt, Tinh thần sẵn sàng và không ngại rèn luyện bản thân trong môi trường có áp lực công việc để lớn!"],
            benefit: ["• Lương cứng + kèm bonus.",
                "• Cơ hội trải nghiệm thực tế, thực chiến chuyên môn, học tập và làm việc trong môi trường nhiều nhân sự trẻ, năng động. Tham gia vào các hoạt động sinh hoạt đoàn thể...."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: true,
            email: "ecpay.contact@gmail.com",
            phone: "19007911",
            address: "Quận Gò Vấp, Hồ Chí Minh, Thành phố Hồ Chí Minh"

        }, {
            company_name: "Công Ty SoftOne",
            image_link: "https://cdn.mywork.com.vn/company-logo-medium/052020/bhj0AZryRLs4jKCU4QsQjGsfPJR6u9cluNGKlFA8.jpeg",
            title: "Thực tập sinh Content marketing",
            job_type: "Nhân viên",
            tag_list: [],
            id_job: 20,
            type: "Toàn thời gian",
            salary: "4,000,000",
            company_address: "Quận Gò Vấp, Hồ Chí Minh, Thành phố Hồ Chí Minh",
            description: ["• Xây dựng nội dung Email Marketing",
                "• Lên nội dung cho các ấn phẩm truyền thông.",
                "• Làm một số công việc theo dự án trong phòng marketing.",
                "• Thực hiện các công tác khác nếu có"],
            require: ["• Là sinh viên các trường Đại học từ năm 3 trở đi hoặc mới ra trường, Ưu tiên các sinh viên đang theo học đúng chuyên ngành thực tập..",
                "• Ham học hỏi, Tư duy tốt, Tinh thần sẵn sàng và không ngại rèn luyện bản thân trong môi trường có áp lực công việc để lớn!"],
            benefit: ["• Lương cứng + kèm bonus.",
                "• Cơ hội trải nghiệm thực tế, thực chiến chuyên môn, học tập và làm việc trong môi trường nhiều nhân sự trẻ, năng động. Tham gia vào các hoạt động sinh hoạt đoàn thể...."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: true,
            email: "softone.company@gmail.com",
            phone: "19007780",
            address: "Quận Gò Vấp, Hồ Chí Minh, Thành phố Hồ Chí Minh"

        }, {
            company_name: "GUfoods",
            image_link: "https://images.glints.com/unsafe/1200x0/glints-dashboard.s3.amazonaws.com/company-logo/b99aea80edd56c93b1aca5fa1c9200a9.jpg",
            title: "Thực tập sinh Logistics",
            job_type: "Nhân viên",
            tag_list: [],
            id_job: 21,
            type: "Toàn thời gian",
            salary: "4,000,000",
            company_address: "Quận 12, Hồ Chí Minh, Thành phố Hồ Chí Minh",
            description: ["• Tiếp nhận, kiểm đếm hàng hoá và nhập vào hệ thống kho",
                "• Xác nhận đơn hàng và nhập liệu vào phần mềm quản lý hàng hoá.",
                "• Cập nhật, kiểm soát và báo cáo số tồn kho định kỳ.",
                "• Tính toán, chuẩn bị hàng hóa để nhập vào các kho đối tác 3PL (Tiki, Lazada,...)",
                "• Tìm kiếm và làm việc với các đối tác vận chuyển",
                "• Tiếp nhận các phản ánh của khách hàng trong khâu đóng gói và giao hàng để cải thiện chất lượng dịch vụ"],
            require: ["• Tốt nghiệp đại học / cao đẳng các khối ngành Logistics, Kho vận, Thương mại (điện tử),...",
                "• Ham học hỏi, Tư duy tốt, Tinh thần sẵn sàng và không ngại rèn luyện bản thân trong môi trường có áp lực công việc để lớn!",
                "Chấp nhận những bạn không có bằng cấp hay background trong ngành, miễn có năng lực, sức khoẻ tốt và cố gắng học hỏi"],
            benefit: ["• Lương cứng + kèm bonus.", "Trợ cấp thực tập (thoả thuận)", "Hỗ trợ đóng dấu xác nhận thực tập",
                "• Cơ hội trải nghiệm thực tế, thực chiến chuyên môn, học tập và làm việc trong môi trường nhiều nhân sự trẻ, năng động. Tham gia vào các hoạt động sinh hoạt đoàn thể...."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: true,
            email: "contact@gufoods.com.vn",
            phone: "19001260",
            address: "Quận 12, Hồ Chí Minh, Thành phố Hồ Chí Minh"

        }, {
            company_name: "Công Ty Lofivn",
            image_link: "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/14c59e864dd16e77d9f77350e8429f07.png",
            title: "Thực tập sinh lập trình",
            job_type: "Nhân viên",
            tag_list: [],
            id_job: 22,
            type: "Toàn thời gian",
            salary: "4,000,000",
            company_address: "Lầu 6 toà nhà GT Building, 403 Nguyễn Thái Bình, Phường 12, Quận Tân Bình, TP. HCM",
            description: ["• Thời gian làm việc: tối thiểu 4 ngày/ tuần.",
                "• Có thể linh động theo lịch học. Hình thức thực tập part-time và thực tập full-time.",
                "•  Địa điểm làm việc: Lầu 6 toà nhà GT Building, 403 Nguyễn Thái Bình, Phường 12, Quận Tân Bình, TP. HCM."],
            require: ["• Đối với thực tập sinh: Không yêu cầu kinh nghiệm",
                "• Thực tập thiết kế website: biết html, css js căn bản,… (biết wordpress, php là một điểm cộng )",
                "Thực tập frontend reactjs: biết reactjs căn bản, biết html, css, js…"],
            benefit: ["• Lương cứng + kèm bonus.", "Trợ cấp thực tập (thoả thuận)", "Hỗ trợ đóng dấu xác nhận thực tập", "Cơ hội trở thành nhân viên chính thức của LOFIVN",
                "• Cơ hội trải nghiệm thực tế, thực chiến chuyên môn, học tập và làm việc trong môi trường nhiều nhân sự trẻ, năng động. Tham gia vào các hoạt động sinh hoạt đoàn thể...."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: true,
            email: "info@lofi.com.vn",
            phone: "19001654",
            address: "Lầu 6 toà nhà GT Building, 403 Nguyễn Thái Bình, Phường 12, Quận Tân Bình, TP. HCM"

        }, {
            company_name: "Công Ty Lofivn",
            image_link: "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/14c59e864dd16e77d9f77350e8429f07.png",
            title: "Thực tập sinh lập trình",
            job_type: "Nhân viên",
            tag_list: [],
            id_job: 23,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Lầu 6 toà nhà GT Building, 403 Nguyễn Thái Bình, Phường 12, Quận Tân Bình, TP. HCM",
            description: ["• Thời gian làm việc: tối thiểu 4 ngày/ tuần.",
                "• Có thể linh động theo lịch học. Hình thức thực tập part-time và thực tập full-time.",
                "•  Địa điểm làm việc: Lầu 6 toà nhà GT Building, 403 Nguyễn Thái Bình, Phường 12, Quận Tân Bình, TP. HCM."],
            require: ["• Đối với thực tập sinh: Không yêu cầu kinh nghiệm",
                "• Thực tập thiết kế website: biết html, css js căn bản,… (biết wordpress, php là một điểm cộng )",
                "Thực tập frontend reactjs: biết reactjs căn bản, biết html, css, js…"],
            benefit: ["• Lương cứng + kèm bonus.", "Trợ cấp thực tập (thoả thuận)", "Hỗ trợ đóng dấu xác nhận thực tập", "Cơ hội trở thành nhân viên chính thức của LOFIVN",
                "• Cơ hội trải nghiệm thực tế, thực chiến chuyên môn, học tập và làm việc trong môi trường nhiều nhân sự trẻ, năng động. Tham gia vào các hoạt động sinh hoạt đoàn thể...."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: true,
            email: "info@lofi.com.vn",
            phone: "19001654",
            address: "Lầu 6 toà nhà GT Building, 403 Nguyễn Thái Bình, Phường 12, Quận Tân Bình, TP. HCM"

        }, {
            company_name: "Cafe An An",
            image_link: "",
            title: "Nhân viên phục vụ",
            job_type: "Nhân viên cửa hàng",
            tag_list: [],
            id_job: 24,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Quận 5, thành phố Hồ Chí Minh",
            description: ["• Quán cafe mình quán nhỏ nên cần 1 bạn nữ chịu khó muốn làm thêm.",
                "• Nhiệm vụ chỉ phục vụ với rửa ly.",
                "• Làm từ 17h30 tới 22h30(5 tiếng)"],
            require: ["• Các bạn học sinh, sinh viên đủ 18 tuổi trở lên có khả năng làm từ 24h/ tuần trở lên (tương đương 4-5 ca làm việc/ tuần, mỗi ca 5-6 tiếng).",
                "• Nhanh nhẹn, hoạt bát, siêng năng, tính tình trung thực, nắm bắt vấn đề nhanh",
                "• Sức khỏe tốt, siêng năng, chủ động trong công việc."],
            benefit: ["• Chế độ phúc lợi tốt, được thưởng lễ tết.", "• Được đào tạo nâng cao nghiệp vụ trong quá trình làm việc.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người.", "• Có cơ hội thăng tiến cao trong công việc."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: true,
            email: "annguyen@gmail.com",
            phone: "0715648797",
            address: "Quận 5, thành phố Hồ Chí Minh"

        }, {
            company_name: "Cafe Trịnh",
            image_link: "",
            title: "Nhân viên phục vụ",
            job_type: "Nhân viên cửa hàng",
            tag_list: [],
            id_job: 25,
            type: "Bán thời gian",
            salary: "2,500,000",
            company_address: "c",
            description: ["• Quán cafe mình quán nhỏ nên cần 1 bạn nữ chịu khó muốn làm thêm.",
                "• Nhiệm vụ chỉ phục vụ với rửa ly.",
                "• Làm từ 17h30 tới 22h30(5 tiếng)"],
            require: ["• Các bạn học sinh, sinh viên đủ 18 tuổi trở lên có khả năng làm từ 24h/ tuần trở lên (tương đương 4-5 ca làm việc/ tuần, mỗi ca 5-6 tiếng).",
                "• Nhanh nhẹn, hoạt bát, siêng năng, tính tình trung thực, nắm bắt vấn đề nhanh",
                "• Sức khỏe tốt, siêng năng, chủ động trong công việc."],
            benefit: ["• Chế độ phúc lợi tốt, được thưởng lễ tết.", "• Được đào tạo nâng cao nghiệp vụ trong quá trình làm việc.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người.", "• Có cơ hội thăng tiến cao trong công việc."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: true,
            email: "trinhtranle@gmail.com",
            phone: "0965264897",
            address: "Quận 9, thành phố Hồ Chí Minh"

        }, {
            company_name: "Cafe Rainbow",
            image_link: "",
            title: "Nhân viên phục vụ",
            job_type: "Nhân viên cửa hàng",
            tag_list: [],
            id_job: 26,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Quận 8, thành phố Hồ Chí Minh",
            description: ["• Quán cafe mình quán nhỏ nên cần 1 bạn nữ chịu khó muốn làm thêm.",
                "• Nhiệm vụ chỉ phục vụ với rửa ly.",
                "• Làm từ 17h30 tới 22h30(5 tiếng)"],
            require: ["• Các bạn học sinh, sinh viên đủ 18 tuổi trở lên có khả năng làm từ 24h/ tuần trở lên (tương đương 4-5 ca làm việc/ tuần, mỗi ca 5-6 tiếng).",
                "• Nhanh nhẹn, hoạt bát, siêng năng, tính tình trung thực, nắm bắt vấn đề nhanh",
                "• Sức khỏe tốt, siêng năng, chủ động trong công việc."],
            benefit: ["• Chế độ phúc lợi tốt, được thưởng lễ tết.", "• Được đào tạo nâng cao nghiệp vụ trong quá trình làm việc.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người.", "• Có cơ hội thăng tiến cao trong công việc."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: true,
            email: "rainbow.cf@gmail.com",
            phone: "0121654789",
            address: "Quận 8, thành phố Hồ Chí Minh"

        }, {
            company_name: "Cafe tại Hồ Chí Minh",
            image_link: "",
            title: "Nhân viên phục vụ",
            job_type: "Nhân viên cửa hàng",
            tag_list: [],
            id_job: 27,
            type: "Bán thời gian",
            salary: "2,500,000",
            company_address: "Quận 1, thành phố Hồ Chí Minh",
            description: ["• Quán cafe mình quán nhỏ nên cần 1 bạn nữ chịu khó muốn làm thêm.",
                "• Nhiệm vụ chỉ phục vụ với rửa ly.",
                "• Làm từ 17h30 tới 22h30(5 tiếng)"],
            require: ["• Các bạn học sinh, sinh viên đủ 18 tuổi trở lên có khả năng làm từ 24h/ tuần trở lên (tương đương 4-5 ca làm việc/ tuần, mỗi ca 5-6 tiếng).",
                "• Nhanh nhẹn, hoạt bát, siêng năng, tính tình trung thực, nắm bắt vấn đề nhanh",
                "• Sức khỏe tốt, siêng năng, chủ động trong công việc."],
            benefit: ["• Chế độ phúc lợi tốt, được thưởng lễ tết.", "• Được đào tạo nâng cao nghiệp vụ trong quá trình làm việc.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người.", "• Có cơ hội thăng tiến cao trong công việc."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: true,
            email: "namtran011@gmail.com",
            phone: "013254989",
            address: "Quận 1, thành phố Hồ Chí Minh"

        }, {
            company_name: "Cafe Vỹ Dạ Xưa",
            image_link: "",
            title: "Nhân viên phục vụ",
            job_type: "Nhân viên cửa hàng",
            tag_list: [],
            id_job: 28,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Quận 2, thành phố Hồ Chí Minh",
            description: ["• Quán cafe mình quán nhỏ nên cần 1 bạn nữ chịu khó muốn làm thêm.",
                "• Nhiệm vụ chỉ phục vụ với rửa ly.",
                "• Làm từ 17h30 tới 22h30(5 tiếng)"],
            require: ["• Các bạn học sinh, sinh viên đủ 18 tuổi trở lên có khả năng làm từ 24h/ tuần trở lên (tương đương 4-5 ca làm việc/ tuần, mỗi ca 5-6 tiếng).",
                "• Nhanh nhẹn, hoạt bát, siêng năng, tính tình trung thực, nắm bắt vấn đề nhanh",
                "• Sức khỏe tốt, siêng năng, chủ động trong công việc."],
            benefit: ["• Chế độ phúc lợi tốt, được thưởng lễ tết.", "• Được đào tạo nâng cao nghiệp vụ trong quá trình làm việc.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người.", "• Có cơ hội thăng tiến cao trong công việc."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: true,
            email: "lien.phan@gmail.com",
            phone: "0121486789",
            address: "Quận 2, thành phố Hồ Chí Minh"

        }, {
            company_name: "Cafe tại Hồ Chí Minh",
            image_link: "",
            title: "Nhân viên phục vụ",
            job_type: "Nhân viên cửa hàng",
            tag_list: [],
            id_job: 29,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Quận 12, thành phố Hồ Chí Minh",
            description: ["• Quán cafe mình quán nhỏ nên cần 1 bạn nữ chịu khó muốn làm thêm.",
                "• Nhiệm vụ chỉ phục vụ với rửa ly.",
                "• Làm từ 17h30 tới 22h30(5 tiếng)"],
            require: ["• Các bạn học sinh, sinh viên đủ 18 tuổi trở lên có khả năng làm từ 24h/ tuần trở lên (tương đương 4-5 ca làm việc/ tuần, mỗi ca 5-6 tiếng).",
                "• Nhanh nhẹn, hoạt bát, siêng năng, tính tình trung thực, nắm bắt vấn đề nhanh",
                "• Sức khỏe tốt, siêng năng, chủ động trong công việc."],
            benefit: ["• Chế độ phúc lợi tốt, được thưởng lễ tết.", "• Được đào tạo nâng cao nghiệp vụ trong quá trình làm việc.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người.", "• Có cơ hội thăng tiến cao trong công việc."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: true,
            email: "nguyenvi.911@gmail.com",
            phone: "0123456789",
            address: "Quận 12, thành phố Hồ Chí Minh"

        },
    ],
    NEW_JOB: [
        {
            company_name: "Đại lý bán bột Yến Mạch quận",
            image_link: "",
            title: "Nhân viên bán hàng",
            job_type: "Nhân viên bán hàng",
            tag_list: [],
            id_job: 13,
            type: "Bán thời gian",
            salary: "3,000,000",
            company_address: "Quận Gò Vấp, Hồ Chí Minh, Thành phố Hồ Chí Minh",
            description: ["• Cần 3 bạn bán bột yết mạch mattcha,.... tại khu vực quận Gò Vấp",
                "• Chủ động, nhanh nhẹn trong việc học hỏi."],
            require: ["• Tuổi từ 18 ~ 30 tuổi, tốt nghiệp THPT.",
                "• Ứng sử tốt"],
            benefit: ["• Lương cứng + kèm bonus.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: "hoạt động"

        }, {
            company_name: "Công ty TNHH Vòng Tròn Đỏ",
            image_link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBtmE5u0HTHkD8cmS9ilCnQ8YgkZDHG7gfLItW_I7LcJ2ImtwMZoAKnyMwTkp4oA16-hE&usqp=CAU",
            title: "Nhân viên bán hàng",
            job_type: "Nhân viên bán hàng",
            tag_list: [],
            id_job: 14,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Quận Gò Vấp, Hồ Chí Minh, Thành phố Hồ Chí Minh",
            description: ["• Chào hỏi và phục vụ khách hàng thân thiện, nhanh nhẹn, nhiệt tình",
                "• Chủ động, nhanh nhẹn trong việc học hỏi.",
                "• Tính tiền và giới thiệu sản phẩm, chương trình khuyến mãi cho khách hàng",
                "• Vệ sinh hàng hóa, quầy kệ, khu vực làm việc tại cửa hàng"],
            require: ["• Tuổi từ 18 ~ 30 tuổi, tốt nghiệp THPT.",
                "• Ứng sử tốt"],
            benefit: ["• Lương cứng + kèm bonus.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: "hoạt động"

        }, {
            company_name: "Công ty TNHH Vòng Tròn Đỏ",
            image_link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBtmE5u0HTHkD8cmS9ilCnQ8YgkZDHG7gfLItW_I7LcJ2ImtwMZoAKnyMwTkp4oA16-hE&usqp=CAU",
            title: "Nhân viên bán hàng",
            job_type: "Nhân viên bán hàng",
            tag_list: [],
            id_job: 15,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Quận 7, Hồ Chí Minh, Thành phố Hồ Chí Minh",
            description: ["• Chào hỏi và phục vụ khách hàng thân thiện, nhanh nhẹn, nhiệt tình",
                "• Chủ động, nhanh nhẹn trong việc học hỏi.",
                "• Tính tiền và giới thiệu sản phẩm, chương trình khuyến mãi cho khách hàng",
                "• Vệ sinh hàng hóa, quầy kệ, khu vực làm việc tại cửa hàng"],
            require: ["• Tuổi từ 18 ~ 30 tuổi, tốt nghiệp THPT.",
                "• Ứng sử tốt"],
            benefit: ["• Lương cứng + kèm bonus.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: "hoạt động"

        }, {
            company_name: "Công ty TNHH Vòng Tròn Đỏ",
            image_link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBtmE5u0HTHkD8cmS9ilCnQ8YgkZDHG7gfLItW_I7LcJ2ImtwMZoAKnyMwTkp4oA16-hE&usqp=CAU",
            title: "Nhân viên bán hàng",
            job_type: "Nhân viên bán hàng",
            tag_list: [],
            id_job: 15,
            type: "Toàn thời gian",
            salary: "5,000,000",
            company_address: "Quận 7, Hồ Chí Minh, Thành phố Hồ Chí Minh",
            description: ["• Chào hỏi và phục vụ khách hàng thân thiện, nhanh nhẹn, nhiệt tình",
                "• Chủ động, nhanh nhẹn trong việc học hỏi.",
                "• Tính tiền và giới thiệu sản phẩm, chương trình khuyến mãi cho khách hàng",
                "• Vệ sinh hàng hóa, quầy kệ, khu vực làm việc tại cửa hàng"],
            require: ["• Tuổi từ 18 ~ 30 tuổi, tốt nghiệp THPT.",
                "• Ứng sử tốt"],
            benefit: ["• Lương cứng + kèm bonus.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: "hoạt động"

        }, {
            company_name: "Công ty TNHH Vòng Tròn Đỏ",
            image_link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBtmE5u0HTHkD8cmS9ilCnQ8YgkZDHG7gfLItW_I7LcJ2ImtwMZoAKnyMwTkp4oA16-hE&usqp=CAU",
            title: "Nhân viên bán hàng",
            job_type: "Nhân viên bán hàng",
            tag_list: [],
            id_job: 16,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Quận Bình Thạnh, Hồ Chí Minh, Thành phố Hồ Chí Minh",
            description: ["• Chào hỏi và phục vụ khách hàng thân thiện, nhanh nhẹn, nhiệt tình",
                "• Chủ động, nhanh nhẹn trong việc học hỏi.",
                "• Tính tiền và giới thiệu sản phẩm, chương trình khuyến mãi cho khách hàng",
                "• Vệ sinh hàng hóa, quầy kệ, khu vực làm việc tại cửa hàng"],
            require: ["• Tuổi từ 18 ~ 30 tuổi, tốt nghiệp THPT.",
                "• Ứng sử tốt"],
            benefit: ["• Lương cứng + kèm bonus.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: "hoạt động"

        }, {
            company_name: "Công ty TNHH Vòng Tròn Đỏ",
            image_link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBtmE5u0HTHkD8cmS9ilCnQ8YgkZDHG7gfLItW_I7LcJ2ImtwMZoAKnyMwTkp4oA16-hE&usqp=CAU",
            title: "Nhân viên bảo vệ",
            job_type: "Nhân viên bảo vệ",
            tag_list: [],
            id_job: 17,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Quận Gò Vấp, Hồ Chí Minh, Thành phố Hồ Chí Minh",
            description: ["• Chào hỏi và phục vụ khách hàng thân thiện, nhanh nhẹn, nhiệt tình",
                "• Chủ động, nhanh nhẹn trong việc học hỏi."],
            require: ["• Tuổi từ 18 ~ 30 tuổi, tốt nghiệp THPT.",
                "• Ứng sử tốt"],
            benefit: ["• Lương cứng + kèm bonus.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: "hoạt động"

        }, {
            company_name: "Công ty cổ phần Beemart",
            image_link: "https://tea-3.lozi.vn/v1/images/resized/beemart-1531826021-1-6102678-1531891148?w=640&type=s",
            title: "Thực tập sinh",
            job_type: "Nhân viên",
            tag_list: [],
            id_job: 18,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Quận Gò Vấp, Hồ Chí Minh, Thành phố Hồ Chí Minh",
            description: ["• Sinh viên Đại học năm 2 đến năm cuối hoặc mới ra trường",
                "• Chủ động, nhanh nhẹn trong việc học hỏi.",
                "• Part-time 4h/ ngày , tối thiểu 24h/ tuần . Dự kiến chương trình thực tập trong 3 tháng.",
                "• Quản lý hàng hóa, Support hàng hóa cho các điểm cửa hàng"],
            require: ["• Là sinh viên các trường Đại học từ năm 3 trở đi hoặc mới ra trường, Ưu tiên các sinh viên đang theo học đúng chuyên ngành thực tập..",
                "• Ham học hỏi, Tư duy tốt, Tinh thần sẵn sàng và không ngại rèn luyện bản thân trong môi trường có áp lực công việc để lớn!",
                "• Có niềm yêu thích và kiến thức về Các loại Bánh là một điểm cộng."],
            benefit: ["• Lương cứng + kèm bonus.",
                "• Cơ hội trải nghiệm thực tế, thực chiến chuyên môn, học tập và làm việc trong môi trường nhiều nhân sự trẻ, năng động. Tham gia vào các hoạt động sinh hoạt đoàn thể...."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: "hoạt động"

        }, {
            company_name: "Công ty ECPay",
            image_link: "https://haymora.com/upload/images/cong_nghe_thong_tin/phan_mem/ecpay/ecpay.jpg",
            title: "Thực tập sinh Tuyển dụng",
            job_type: "Nhân viên",
            tag_list: [],
            id_job: 19,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Quận Gò Vấp, Hồ Chí Minh, Thành phố Hồ Chí Minh",
            description: ["• Thực hiện các công tác đăng tuyển, sàng lọc, setup phỏng vấn",
                "• Tham gia công tác phỏng vấn.",
                "• Các thủ tục thư mời làm việc và tiếp nhận nhân sự mới.",
                "• Thực hiện các công tác khác nếu có"],
            require: ["• Là sinh viên các trường Đại học từ năm 3 trở đi hoặc mới ra trường, Ưu tiên các sinh viên đang theo học đúng chuyên ngành thực tập..",
                "• Ham học hỏi, Tư duy tốt, Tinh thần sẵn sàng và không ngại rèn luyện bản thân trong môi trường có áp lực công việc để lớn!"],
            benefit: ["• Lương cứng + kèm bonus.",
                "• Cơ hội trải nghiệm thực tế, thực chiến chuyên môn, học tập và làm việc trong môi trường nhiều nhân sự trẻ, năng động. Tham gia vào các hoạt động sinh hoạt đoàn thể...."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: "hoạt động"

        }, {
            company_name: "Công Ty SoftOne",
            image_link: "https://cdn.mywork.com.vn/company-logo-medium/052020/bhj0AZryRLs4jKCU4QsQjGsfPJR6u9cluNGKlFA8.jpeg",
            title: "Thực tập sinh Content marketing",
            job_type: "Nhân viên",
            tag_list: [],
            id_job: 20,
            type: "Toàn thời gian",
            salary: "4,000,000",
            company_address: "Quận Gò Vấp, Hồ Chí Minh, Thành phố Hồ Chí Minh",
            description: ["• Xây dựng nội dung Email Marketing",
                "• Lên nội dung cho các ấn phẩm truyền thông.",
                "• Làm một số công việc theo dự án trong phòng marketing.",
                "• Thực hiện các công tác khác nếu có"],
            require: ["• Là sinh viên các trường Đại học từ năm 3 trở đi hoặc mới ra trường, Ưu tiên các sinh viên đang theo học đúng chuyên ngành thực tập..",
                "• Ham học hỏi, Tư duy tốt, Tinh thần sẵn sàng và không ngại rèn luyện bản thân trong môi trường có áp lực công việc để lớn!"],
            benefit: ["• Lương cứng + kèm bonus.",
                "• Cơ hội trải nghiệm thực tế, thực chiến chuyên môn, học tập và làm việc trong môi trường nhiều nhân sự trẻ, năng động. Tham gia vào các hoạt động sinh hoạt đoàn thể...."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: "hoạt động"

        }, {
            company_name: "GUfoods",
            image_link: "https://images.glints.com/unsafe/1200x0/glints-dashboard.s3.amazonaws.com/company-logo/b99aea80edd56c93b1aca5fa1c9200a9.jpg",
            title: "Thực tập sinh Logistics",
            job_type: "Nhân viên",
            tag_list: [],
            id_job: 21,
            type: "Toàn thời gian",
            salary: "4,000,000",
            company_address: "Quận 12, Hồ Chí Minh, Thành phố Hồ Chí Minh",
            description: ["• Tiếp nhận, kiểm đếm hàng hoá và nhập vào hệ thống kho",
                "• Xác nhận đơn hàng và nhập liệu vào phần mềm quản lý hàng hoá.",
                "• Cập nhật, kiểm soát và báo cáo số tồn kho định kỳ.",
                "• Tính toán, chuẩn bị hàng hóa để nhập vào các kho đối tác 3PL (Tiki, Lazada,...)",
                "• Tìm kiếm và làm việc với các đối tác vận chuyển",
                "• Tiếp nhận các phản ánh của khách hàng trong khâu đóng gói và giao hàng để cải thiện chất lượng dịch vụ"],
            require: ["• Tốt nghiệp đại học / cao đẳng các khối ngành Logistics, Kho vận, Thương mại (điện tử),...",
                "• Ham học hỏi, Tư duy tốt, Tinh thần sẵn sàng và không ngại rèn luyện bản thân trong môi trường có áp lực công việc để lớn!",
                "Chấp nhận những bạn không có bằng cấp hay background trong ngành, miễn có năng lực, sức khoẻ tốt và cố gắng học hỏi"],
            benefit: ["• Lương cứng + kèm bonus.", "Trợ cấp thực tập (thoả thuận)", "Hỗ trợ đóng dấu xác nhận thực tập",
                "• Cơ hội trải nghiệm thực tế, thực chiến chuyên môn, học tập và làm việc trong môi trường nhiều nhân sự trẻ, năng động. Tham gia vào các hoạt động sinh hoạt đoàn thể...."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: "hoạt động"

        }, {
            company_name: "Công Ty Lofivn",
            image_link: "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/14c59e864dd16e77d9f77350e8429f07.png",
            title: "Thực tập sinh lập trình",
            job_type: "Nhân viên",
            tag_list: [],
            id_job: 22,
            type: "Toàn thời gian",
            salary: "4,000,000",
            company_address: "Lầu 6 toà nhà GT Building, 403 Nguyễn Thái Bình, Phường 12, Quận Tân Bình, TP. HCM",
            description: ["• Thời gian làm việc: tối thiểu 4 ngày/ tuần.",
                "• Có thể linh động theo lịch học. Hình thức thực tập part-time và thực tập full-time.",
                "•  Địa điểm làm việc: Lầu 6 toà nhà GT Building, 403 Nguyễn Thái Bình, Phường 12, Quận Tân Bình, TP. HCM."],
            require: ["• Đối với thực tập sinh: Không yêu cầu kinh nghiệm",
                "• Thực tập thiết kế website: biết html, css js căn bản,… (biết wordpress, php là một điểm cộng )",
                "Thực tập frontend reactjs: biết reactjs căn bản, biết html, css, js…"],
            benefit: ["• Lương cứng + kèm bonus.", "Trợ cấp thực tập (thoả thuận)", "Hỗ trợ đóng dấu xác nhận thực tập", "Cơ hội trở thành nhân viên chính thức của LOFIVN",
                "• Cơ hội trải nghiệm thực tế, thực chiến chuyên môn, học tập và làm việc trong môi trường nhiều nhân sự trẻ, năng động. Tham gia vào các hoạt động sinh hoạt đoàn thể...."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: "hoạt động"

        }
    ],
    HOT_JOB: [
        {
            company_name: "The coffee house",
            image_link: "https://rubee.com.vn/admin/webroot/upload/image/images/tin-tuc/the-coffee-house-logo-2.jpg",
            title: "Nhân viên cửa hàng",
            job_type: "Phục vụ",
            tag_list: [],
            id_job: 0,
            type: "Bán thời gian",
            salary: "3,000,000",
            company_address: "quận Tân Bình, thành phố Hồ Chí Minh",
            description: ["• Phục vụ khách hàng.",
                "• Đảm bảo vệ sinh cửa hàng làm việc.",
                "• Hỗ trợ các công việc trong quầy và sảnh theo sự sắp xếp của Quản lý cửa hàng."],
            require: ["• Các bạn học sinh, sinh viên đủ 18 tuổi trở lên có khả năng làm từ 24h/ tuần trở lên (tương đương 4-5 ca làm việc/ tuần, mỗi ca 5-6 tiếng).",
                "• Đam mê & muốn tích lũy kinh nghiệm làm việc trong ngành dịch vụ F&B ở các mảng (phục vụ khách hàng, pha chế)",
                "• Sức khỏe tốt, siêng năng, chủ động trong công việc."],
            benefit: ["• Làm việc trong môi trường dịch vụ chuyên nghiệp.", "• Được học hỏi, đào tạo và phát triển kỹ năng pha chế & thu ngân (nếu muốn).",
                "• Cơ hội thăng tiến nhanh lên các vị trí quản lý với các cửa hàng mới mở hằng tuần.", "• Các chương trình ưu đãi dành cho nhân viên TCH."],
            date_create: "10/06/2021",
            duration: "10/08/2021",
            status: "hoạt động"

        }, {
            company_name: "The coffee house",
            image_link: "https://rubee.com.vn/admin/webroot/upload/image/images/tin-tuc/the-coffee-house-logo-2.jpg",
            title: "Nhân viên cửa hàng",
            job_type: "Phục vụ",
            tag_list: [],
            id_job: 1,
            type: "Toàn thời gian",
            salary: "7,000,000",
            company_address: "Quận 1, thành phố Hồ Chí Minh",
            description: ["• Phục vụ khách hàng.",
                "• Đảm bảo vệ sinh cửa hàng làm việc.",
                "• Hỗ trợ các công việc trong quầy và sảnh theo sự sắp xếp của Quản lý cửa hàng."],
            require: ["• Các bạn học sinh, sinh viên đủ 18 tuổi trở lên có khả năng làm từ 24h/ tuần trở lên (tương đương 4-5 ca làm việc/ tuần, mỗi ca 5-6 tiếng).",
                "• Đam mê & muốn tích lũy kinh nghiệm làm việc trong ngành dịch vụ F&B ở các mảng (phục vụ khách hàng, pha chế)",
                "• Sức khỏe tốt, siêng năng, chủ động trong công việc."],
            benefit: ["• Làm việc trong môi trường dịch vụ chuyên nghiệp.", "• Được học hỏi, đào tạo và phát triển kỹ năng pha chế & thu ngân (nếu muốn).",
                "• Cơ hội thăng tiến nhanh lên các vị trí quản lý với các cửa hàng mới mở hằng tuần.", "• Các chương trình ưu đãi dành cho nhân viên TCH."],
            date_create: "10/06/2021",
            duration: "10/08/2021",
            status: "hoạt động"

        }, {
            company_name: "CÔNG TY CP HÀNG TIÊU DÙNG MASAN",
            image_link: "https://cdn.brvn.vn/news/480px/2013/masanhuydongvon0_1373616909.jpg",
            title: "Nhân Viên Bán Hàng",
            job_type: "Bán hàng",
            tag_list: [],
            id_job: 2,
            type: "Bán thời gian",
            salary: "3,000,000",
            company_address: " MPlaza, 39 Lê Duẩn, Bến Nghé, Quận 1, Hồ Chí Minh",
            description: ["• Thực hiện chia chọn hàng hóa theo hướng dẫn",
                "• Chịu KPI bán hàng theo target mỗi ngày",
                "• Nhiệt tình, vui vẻ, không ngại việc"],
            require: ["• Các bạn học sinh, sinh viên đủ 18 tuổi trở lên có khả năng làm từ 24h/ tuần trở lên (tương đương 4-5 ca làm việc/ tuần, mỗi ca 5-6 tiếng).",
                "• Nhanh nhẹn, hoạt bát, siêng năng, tính tình trung thực, nắm bắt vấn đề nhanh, có tố chất sales",
                "• Sức khỏe tốt, siêng năng, chủ động trong công việc."],
            benefit: ["• Chế độ phúc lợi tốt, được thưởng lễ tết.", "• Được đào tạo nâng cao nghiệp vụ trong quá trình làm việc.",
                "• Được làm việc trong môi trường chuyên nghiệp, năng động và hiệu quả.", "• Có cơ hội thăng tiến cao trong công việc."],
            date_create: "01/06/2021",
            duration: "01/08/2021",
            status: "hoạt động"

        }, {
            company_name: "Công Ty Tnhh A.N Sài Gòn Group",
            image_link: "https://cdn1.timviecnhanh.com/images/default/2021/06/18/images/162400169835.jpeg",
            title: "Thu Ngân",
            job_type: "Bán hàng",
            tag_list: [],
            id_job: 3,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Số 85 Đường Số 6, Ấp Tiền Lân, Xã Bà Điểm, Huyện Hóc Môn, Thành phố Hồ Chí Minh",
            description: ["• Tính tiền cho khách",
                "• Kiểm tra hóa đơn, chứng từ cuối ngày",
                "• Hỗ trợ bán đồ ăn chín tại quầy"],
            require: ["• Các bạn học sinh, sinh viên đủ 18 tuổi trở lên có khả năng làm từ 24h/ tuần trở lên (tương đương 4-5 ca làm việc/ tuần, mỗi ca 5-6 tiếng).",
                "• Nhanh nhẹn, hoạt bát, siêng năng, tính tình trung thực, nắm bắt vấn đề nhanh",
                "• Sức khỏe tốt, siêng năng, chủ động trong công việc."],
            benefit: ["• Chế độ phúc lợi tốt, được thưởng lễ tết.", "• Được đào tạo nâng cao nghiệp vụ trong quá trình làm việc.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người.", "• Có cơ hội thăng tiến cao trong công việc."],
            date_create: "18/06/2021",
            duration: "18/08/2021",
            status: "hoạt động"

        }, {
            company_name: "CÔNG TY CP PIZZA NGON",
            image_link: "https://cdn1.timviecnhanh.com/asset/home/img/employer/5aa88868f0846_1520994408.png",
            title: "Nhân Viên Call Center",
            job_type: "Call Teller",
            tag_list: [],
            id_job: 4,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Tòa nhà Lottery Tower - Lầu 10, 77 Trần Nhân Tôn, Phường 9, Quận 5, HCM",
            description: ["• Làm việc tại 105-107 Nguyễn Thái Học, P. Cầu Ông Lãnh, Q.1, TP.HCM",
                "• Làm việc part-time theo ca: 4-6 giờ/ca",
                "• Tiếp nhận order của khách hàng",
                "• Giải đáp và tư vấn về sản phẩm và các chương trình khuyến mãi",
                "• Giải quyết các phản hồi, yêu cầu, khiếu nại của khách hàng"],
            require: ["• Có thể làm việc xoay ca linh động (bắt buộc phải làm việc vào thứ 3, thứ 7 và Chủ nhật), có thể làm việc các ngày Lễ, Tết.",
                "• Giọng nói dễ nghe (không ngọng)",
                "• Chịu được áp lực cao về cuộc gọi"],
            benefit: ["• Hưởng lương gấp 3 lần khi làm việc vào Lễ, Tết", "• Được đào tạo nâng cao nghiệp vụ trong quá trình làm việc.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người.", "• Có cơ hội thăng tiến cao trong công việc."],
            date_create: "19/06/2021",
            duration: "19/08/2021",
            status: "hoạt động"

        }, {
            company_name: "CÔNG TY CP PIZZA NGON",
            image_link: "https://cdn1.timviecnhanh.com/asset/home/img/employer/5aa88868f0846_1520994408.png",
            title: "Nhân Viên Part Time",
            job_type: "Bán hàng",
            tag_list: [],
            id_job: 5,
            type: "Bán thời gian",
            salary: "3,000,000",
            company_address: "Tòa nhà Lottery Tower - Lầu 10, 77 Trần Nhân Tôn, Phường 9, Quận 5, HCM",
            description: ["• Tính tiền cho khách",
                "• Kiểm tra hóa đơn, chứng từ cuối ngày",
                "• Hỗ trợ bán đồ ăn chín tại quầy"],
            require: ["• Các bạn học sinh, sinh viên đủ 18 tuổi trở lên có khả năng làm từ 24h/ tuần trở lên (tương đương 4-5 ca làm việc/ tuần, mỗi ca 5-6 tiếng).",
                "• Nhanh nhẹn, hoạt bát, siêng năng, tính tình trung thực, nắm bắt vấn đề nhanh",
                "• Sức khỏe tốt, siêng năng, chủ động trong công việc."],
            benefit: ["• Chế độ phúc lợi tốt, được thưởng lễ tết.", "• Được đào tạo nâng cao nghiệp vụ trong quá trình làm việc.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người.", "• Có cơ hội thăng tiến cao trong công việc."],
            date_create: "19/06/2021",
            duration: "19/08/2021",
            status: "hoạt động"

        }, {
            company_name: "TT Trực Tuyến Workonline 24H",
            image_link: "https://cdn1.timviecnhanh.com/asset/home/img/employer/5ebcabed03b02_1589423085.jpg",
            title: "Nhân Viên Nhập Dữ Liệu",
            job_type: "",
            tag_list: [],
            id_job: 6,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Quận 3, thành phố Hồ Chí Minh",
            description: ["• Công việc chọn giải quyết dử liệu hình ảnh từ phần mềm đưa xuống, làm trên máy vi tính hoặc điện thoại của bạn, không ràng buộc thời gian rảnh lúc nào thì làm, có thể làm tại nhà hoặc bất cử đâu có internet kết nối với máy vi tính hoặc điện thoại. Đăng ký làm việc kiếm tiền trên website: httpS://www.woh247.comg"],
            require: ["• Có kiếm thức cơ bản về sử dụng internet, có máy vi tinh hoặc điện thoại..",
                "•Có tốc độ đánh máy nhanh và chút vốn tiếng anh là một lợi thế.",
                "• Kiên trì xiệng năng trong công việc."],
            benefit: ["• Làm lâu dài sẽ được ưu tiên tăng % tiền thưởng.", "• Lương theo sản lượng.",
                "• Giờ giấc tự do, chủ động được thời gian làm việc."],
            date_create: "19/06/2021",
            duration: "19/08/2021",
            status: "hoạt động"

        }, {
            company_name: "Công Ty Tnhh Ministop Việt Nam",
            image_link: "https://cdn1.timviecnhanh.com/images/default/2021/06/18/images/162400169835.jpeg",
            title: "Nhân Viên Bán Hàng",
            job_type: "Bán hàng",
            tag_list: [],
            id_job: 7,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Số 85 Đường Số 6, Ấp Tiền Lân, Xã Bà Điểm, Huyện Hóc Môn, Thành phố Hồ Chí Minh",
            description: ["• NV quầy bán hàng, thanh toán tính tiền.",
                "• NV quầy giữ đồ, chăm sóc khách hàng.",
                "• NV kiểm kê hàng hóa và hóa đơn hàng.",
                "• MiniStop : Q.1, Q.2 , Q.3, Q.4, Q.5, Q.6, Q.7, Q.8.Q.9, Q.10, Q.11, Phú nhuận. Bình Thạnh.Tân bình, Tân phú"],
            require: ["• Các bạn học sinh, sinh viên đủ 18 tuổi trở lên có khả năng làm từ 24h/ tuần trở lên (tương đương 4-5 ca làm việc/ tuần, mỗi ca 5-6 tiếng).",
                "• Nhanh nhẹn, hoạt bát, siêng năng, tính tình trung thực, nắm bắt vấn đề nhanh",
                "• Sức khỏe tốt, siêng năng, chủ động trong công việc."],
            benefit: ["• Chế độ phúc lợi tốt, được thưởng lễ tết.", "• Được đào tạo nâng cao nghiệp vụ trong quá trình làm việc.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người.", "• Có cơ hội thăng tiến cao trong công việc."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: "hoạt động"

        }, {
            company_name: "Siêu Thị Big C",
            image_link: "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/18158268c55b328c797f859b5fc9add6.png",
            title: "Nhân viên siêu thị",
            job_type: "",
            tag_list: [],
            id_job: 8,
            type: "Bán thời gian",
            salary: "3,000,000",
            company_address: "Hồ Chí Minh, Thành phố Hồ Chí Minh",
            description: ["• NV trực phòng camera.",
                "• NV quầy bán hàng, chăm sóc khách hàng.",
                "• NV quầy rượu, nước hoa, mỹ phẩm, trang sức...",
                "• NV kho, kiểm kê, xuất nhập hàng hóa."],
            require: ["• Các bạn học sinh, sinh viên đủ 18 tuổi trở lên có khả năng làm từ 24h/ tuần trở lên (tương đương 4-5 ca làm việc/ tuần, mỗi ca 5-6 tiếng).",
                "• Nhanh nhẹn, hoạt bát, siêng năng, tính tình trung thực, nắm bắt vấn đề nhanh",
                "• Sức khỏe tốt, siêng năng, chủ động trong công việc."],
            benefit: ["• Chế độ phúc lợi tốt, được thưởng lễ tết.", "• Được đào tạo nâng cao nghiệp vụ trong quá trình làm việc.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người.", "• Có cơ hội thăng tiến cao trong công việc."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: "hoạt động"

        }, {
            company_name: "Digiworld Corporation",
            image_link: "https://media-exp1.licdn.com/dms/image/C4E0BAQFeF_eL00Sg3w/company-logo_200_200/0/1519899505547?e=2159024400&v=beta&t=79aGnfAl0HDtz0ZbWd7G9i_cNlyYo0Oc4zjBp_MQDgY",
            title: "Thực tập sinh Tuyển dụng",
            job_type: "Service",
            tag_list: [],
            id_job: 9,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "231 - 233 Lê Thánh Tôn, Quận 1, thành phố Hồ Chí Minh",
            description: ["• Hỗ trợ công tác truyền thông, tìm kiếm ứng viên theo yêu cầu của công ty.",
                "• Hỗ trợ công tác tuyển chọn (cập nhật hồ sơ ứng viên, set-up phỏng vấn, tiếp đón ứng viên, tham gia phỏng vấn trực tiếp, thông báo kết quả phỏng vấn...).",
                "• Tiếp nhận và xử lý hồ sơ Nhân viên mới",
                "• Lập kế hoạch làm việc, báo cáo kết quả công việc định kỳ lên quản lý trực tiếp."],
            require: ["• Các bạn học sinh, sinh viên đủ 18 tuổi trở lên có khả năng làm từ 24h/ tuần trở lên (tương đương 4-5 ca làm việc/ tuần, mỗi ca 5-6 tiếng).",
                "• Nhanh nhẹn, hoạt bát, siêng năng, tính tình trung thực, nắm bắt vấn đề nhanh",
                "• Sức khỏe tốt, siêng năng, chủ động trong công việc."],
            benefit: ["• Chế độ phúc lợi tốt, được thưởng lễ tết.", "• Được đào tạo nâng cao nghiệp vụ trong quá trình làm việc.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người.", "• Có cơ hội thăng tiến cao trong công việc."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: "hoạt động"

        }, {
            company_name: "Cafe tại Hồ Chí Minh",
            image_link: "",
            title: "Nhân viên phục vụ",
            job_type: "Nhân viên cửa hàng",
            tag_list: [],
            id_job: 10,
            type: "Bán thời gian",
            salary: "2,500,000",
            company_address: "Quận 4, thành phố Hồ Chí Minh",
            description: ["• Quán cafe mình quán nhỏ nên cần 1 bạn nữ chịu khó muốn làm thêm.",
                "• Nhiệm vụ chỉ phục vụ với rửa ly.",
                "• Làm từ 17h30 tới 22h30(5 tiếng)"],
            require: ["• Các bạn học sinh, sinh viên đủ 18 tuổi trở lên có khả năng làm từ 24h/ tuần trở lên (tương đương 4-5 ca làm việc/ tuần, mỗi ca 5-6 tiếng).",
                "• Nhanh nhẹn, hoạt bát, siêng năng, tính tình trung thực, nắm bắt vấn đề nhanh",
                "• Sức khỏe tốt, siêng năng, chủ động trong công việc."],
            benefit: ["• Chế độ phúc lợi tốt, được thưởng lễ tết.", "• Được đào tạo nâng cao nghiệp vụ trong quá trình làm việc.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người.", "• Có cơ hội thăng tiến cao trong công việc."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: "hoạt động"

        }
    ],

    WORK_TYPE: [
        { title: 'Tất cả', },
        { title: 'Bán hàng', },
        { title: 'Thời vụ', },
        { title: 'Công nghệ cao', },
        { title: 'Khác', },
    ],

    WORK_LEVEL: [
        { title: 'Tất cả', },
        { title: 'Sinh viên/thực tập', },
        { title: 'Mới tốt nghiệp', },
        { title: 'Nhân viên', },
        { title: 'Khác', },
    ],

    SALARY_LEVEL: [
        { title: 'Tất cả', },
        { title: '< 3,000,000 VND', },
        { title: '3,000,000 - 5,000,000 VND', },
        { title: '5,000,000 - 8,000,000 VND', },
        { title: '> 8,000,000 VND', },
    ]

};

var data_manage_hr_page = {
    JOB_LIST: [
        {
            company_name: "Công ty TNHH Vòng Tròn Đỏ",
            image_link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBtmE5u0HTHkD8cmS9ilCnQ8YgkZDHG7gfLItW_I7LcJ2ImtwMZoAKnyMwTkp4oA16-hE&usqp=CAU",
            title: "Circle K tuyển nhân viên bán hàng tại Tp.HCM",
            job_type: "Nhân viên bán hàng",
            tag_list: [],
            id_job: 14,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Quận Gò Vấp, Hồ Chí Minh, Thành phố Hồ Chí Minh",
            description: ["• Chào hỏi và phục vụ khách hàng thân thiện, nhanh nhẹn, nhiệt tình",
                "• Chủ động, nhanh nhẹn trong việc học hỏi.",
                "• Tính tiền và giới thiệu sản phẩm, chương trình khuyến mãi cho khách hàng",
                "• Vệ sinh hàng hóa, quầy kệ, khu vực làm việc tại cửa hàng"],
            require: ["• Tuổi từ 18 ~ 30 tuổi, tốt nghiệp THPT.",
                "• Ứng sử tốt"],
            benefit: ["• Lương cứng + kèm bonus.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: true,
            num: 1

        }, {
            company_name: "Công ty TNHH Vòng Tròn Đỏ",
            image_link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBtmE5u0HTHkD8cmS9ilCnQ8YgkZDHG7gfLItW_I7LcJ2ImtwMZoAKnyMwTkp4oA16-hE&usqp=CAU",
            title: "Circle K tuyển nhân viên bán hàng tại Tp.HCM",
            job_type: "Nhân viên bán hàng",
            tag_list: [],
            id_job: 15,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Quận 7, Hồ Chí Minh, Thành phố Hồ Chí Minh",
            description: ["• Chào hỏi và phục vụ khách hàng thân thiện, nhanh nhẹn, nhiệt tình",
                "• Chủ động, nhanh nhẹn trong việc học hỏi.",
                "• Tính tiền và giới thiệu sản phẩm, chương trình khuyến mãi cho khách hàng",
                "• Vệ sinh hàng hóa, quầy kệ, khu vực làm việc tại cửa hàng"],
            require: ["• Tuổi từ 18 ~ 30 tuổi, tốt nghiệp THPT.",
                "• Ứng sử tốt"],
            benefit: ["• Lương cứng + kèm bonus.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: true,
            num: 0

        }, {
            company_name: "Công ty TNHH Vòng Tròn Đỏ",
            image_link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBtmE5u0HTHkD8cmS9ilCnQ8YgkZDHG7gfLItW_I7LcJ2ImtwMZoAKnyMwTkp4oA16-hE&usqp=CAU",
            title: "Circle K tuyển nhân viên bán hàng tại Tp.HCM",
            job_type: "Nhân viên bán hàng",
            tag_list: [],
            id_job: 20,
            type: "Toàn thời gian",
            salary: "5,000,000",
            company_address: "Quận 7, Hồ Chí Minh, Thành phố Hồ Chí Minh",
            description: ["• Chào hỏi và phục vụ khách hàng thân thiện, nhanh nhẹn, nhiệt tình",
                "• Chủ động, nhanh nhẹn trong việc học hỏi.",
                "• Tính tiền và giới thiệu sản phẩm, chương trình khuyến mãi cho khách hàng",
                "• Vệ sinh hàng hóa, quầy kệ, khu vực làm việc tại cửa hàng"],
            require: ["• Tuổi từ 18 ~ 30 tuổi, tốt nghiệp THPT.",
                "• Ứng sử tốt"],
            benefit: ["• Lương cứng + kèm bonus.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: true,
            num: 0

        }, {
            company_name: "Công ty TNHH Vòng Tròn Đỏ",
            image_link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBtmE5u0HTHkD8cmS9ilCnQ8YgkZDHG7gfLItW_I7LcJ2ImtwMZoAKnyMwTkp4oA16-hE&usqp=CAU",
            title: "Circle K tuyển nhân viên bán hàng tại Tp.HCM",
            job_type: "Nhân viên bán hàng",
            tag_list: [],
            id_job: 16,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Quận Bình Thạnh, Hồ Chí Minh, Thành phố Hồ Chí Minh",
            description: ["• Chào hỏi và phục vụ khách hàng thân thiện, nhanh nhẹn, nhiệt tình",
                "• Chủ động, nhanh nhẹn trong việc học hỏi.",
                "• Tính tiền và giới thiệu sản phẩm, chương trình khuyến mãi cho khách hàng",
                "• Vệ sinh hàng hóa, quầy kệ, khu vực làm việc tại cửa hàng"],
            require: ["• Tuổi từ 18 ~ 30 tuổi, tốt nghiệp THPT.",
                "• Ứng sử tốt"],
            benefit: ["• Lương cứng + kèm bonus.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: true,
            num: 0

        }, {
            company_name: "Công ty TNHH Vòng Tròn Đỏ",
            image_link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBtmE5u0HTHkD8cmS9ilCnQ8YgkZDHG7gfLItW_I7LcJ2ImtwMZoAKnyMwTkp4oA16-hE&usqp=CAU",
            title: "Circle K tuyển nhân viên bảo vệ tại Tp.HCM",
            job_type: "Nhân viên bảo vệ",
            tag_list: [],
            id_job: 17,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Quận Gò Vấp, Hồ Chí Minh, Thành phố Hồ Chí Minh",
            description: ["• Chào hỏi và phục vụ khách hàng thân thiện, nhanh nhẹn, nhiệt tình",
                "• Chủ động, nhanh nhẹn trong việc học hỏi."],
            require: ["• Tuổi từ 18 ~ 30 tuổi, tốt nghiệp THPT.",
                "• Ứng sử tốt"],
            benefit: ["• Lương cứng + kèm bonus.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: true,
            num: 0

        }
    ],
    CV_LIST: [
        {
            employee_id: 1,
            employee_name: 'Nguyễn Trí Nhân',
            apply_date: '05/07/2021',
            job_name: 'Nhân viên bán hàng',
            job_link: '/jobs/17',
            status: 1

        }
    ]
}

var loremipsum = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit,'
    + ' sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
    + ' Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
    + ' Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.'
    + ' Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n'
    + '\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium,'
    + ' totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.'
    + ' Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit,'
    + ' sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.'
    + ' Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit,'
    + ' sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.'
    + ' Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?'
    + ' Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur,'
    + ' vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?';

var hr_user = {
    username: "hr@kms.com",
    fullname: "Đặng Văn Hùng",
}

var student_user = {
    username: "nhanntse140284@fpt.edu.vn",
    fullname: "Nguyễn Trí Nhân",
    address: "Quận 9, Thành Phố Hồ Chí Minh",
    phone: "0123456789",
    email: "nhanntse140284@fpt.edu.vn",
    languages: "",
    about: "",
    job_applied: [
        {
            company_name: "The coffee house",
            image_link: "https://rubee.com.vn/admin/webroot/upload/image/images/tin-tuc/the-coffee-house-logo-2.jpg",
            title: "Nhân viên cửa hàng",
            job_type: "Phục vụ",
            tag_list: [],
            id_job: 0,
            type: "Bán thời gian",
            salary: "3,000,000",
            company_address: "quận Tân Bình, thành phố Hồ Chí Minh",
            description: ["• Phục vụ khách hàng.",
                "• Đảm bảo vệ sinh cửa hàng làm việc.",
                "• Hỗ trợ các công việc trong quầy và sảnh theo sự sắp xếp của Quản lý cửa hàng."],
            require: ["• Các bạn học sinh, sinh viên đủ 18 tuổi trở lên có khả năng làm từ 24h/ tuần trở lên (tương đương 4-5 ca làm việc/ tuần, mỗi ca 5-6 tiếng).",
                "• Đam mê & muốn tích lũy kinh nghiệm làm việc trong ngành dịch vụ F&B ở các mảng (phục vụ khách hàng, pha chế)",
                "• Sức khỏe tốt, siêng năng, chủ động trong công việc."],
            benefit: ["• Làm việc trong môi trường dịch vụ chuyên nghiệp.", "• Được học hỏi, đào tạo và phát triển kỹ năng pha chế & thu ngân (nếu muốn).",
                "• Cơ hội thăng tiến nhanh lên các vị trí quản lý với các cửa hàng mới mở hằng tuần.", "• Các chương trình ưu đãi dành cho nhân viên TCH."],
            date_create: "10/06/2021",
            duration: "10/08/2021",
            applied: "20/06/2021"

        },
        {
            company_name: "Công ty TNHH Vòng Tròn Đỏ",
            image_link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBtmE5u0HTHkD8cmS9ilCnQ8YgkZDHG7gfLItW_I7LcJ2ImtwMZoAKnyMwTkp4oA16-hE&usqp=CAU",
            title: "Nhân viên bán hàng",
            job_type: "Nhân viên bán hàng",
            tag_list: [],
            id_job: 14,
            type: "Bán thời gian",
            salary: "2,000,000",
            company_address: "Quận Gò Vấp, Hồ Chí Minh, Thành phố Hồ Chí Minh",
            description: ["• Chào hỏi và phục vụ khách hàng thân thiện, nhanh nhẹn, nhiệt tình",
                "• Chủ động, nhanh nhẹn trong việc học hỏi.",
                "• Tính tiền và giới thiệu sản phẩm, chương trình khuyến mãi cho khách hàng",
                "• Vệ sinh hàng hóa, quầy kệ, khu vực làm việc tại cửa hàng"],
            require: ["• Tuổi từ 18 ~ 30 tuổi, tốt nghiệp THPT.",
                "• Ứng sử tốt"],
            benefit: ["• Lương cứng + kèm bonus.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            applied: "02/07/2021"

        }
    ],
    job_seen: "0",
    job_approve: [
        {
            company_name: "Cafe tại Hồ Chí Minh",
            image_link: "",
            title: "Nhân viên phục vụ",
            job_type: "Nhân viên cửa hàng",
            tag_list: [],
            id_job: 10,
            type: "Bán thời gian",
            salary: "2,500,000",
            company_address: "Quận 4, thành phố Hồ Chí Minh",
            description: ["• Quán cafe mình quán nhỏ nên cần 1 bạn nữ chịu khó muốn làm thêm.",
                "• Nhiệm vụ chỉ phục vụ với rửa ly.",
                "• Làm từ 17h30 tới 22h30(5 tiếng)"],
            require: ["• Các bạn học sinh, sinh viên đủ 18 tuổi trở lên có khả năng làm từ 24h/ tuần trở lên (tương đương 4-5 ca làm việc/ tuần, mỗi ca 5-6 tiếng).",
                "• Nhanh nhẹn, hoạt bát, siêng năng, tính tình trung thực, nắm bắt vấn đề nhanh",
                "• Sức khỏe tốt, siêng năng, chủ động trong công việc."],
            benefit: ["• Chế độ phúc lợi tốt, được thưởng lễ tết.", "• Được đào tạo nâng cao nghiệp vụ trong quá trình làm việc.",
                "• Ca làm việc linh hoạt Part-time & Full-time phù hợp với lịch học sinh viên/lịch cá nhân của từng người.", "• Có cơ hội thăng tiến cao trong công việc."],
            date_create: "20/06/2021",
            duration: "20/08/2021",
            status: true,
            email: "antran1212@gmail.com",
            phone: "0962888475",
            address: "Quận 4, thành phố Hồ Chí Minh",
            applied: "01/07/2021"

        },
    ]
}
var hr_user = {
    username: "hungcirclek@gmail.com",
    fullname: "Trần Văn B",
    address: "Quận 9, Thành Phố Hồ Chí Minh",
    phone: "0123456789",
    email: "hungcirclek@gmail.com",
    languages: "",
    about: ""
}

var report_data = {}

var employees = [
    {
        id: "1",
        fullname: "Đặng Văn Hùng",
        phone: "0354046609",
        email: "hungcirclek@gmail.com",
        status: true,
    },
    {
        id: "2",
        fullname: "Nguyễn Văn A",
        phone: "0851471890",
        email: "a.nguyen@gmail.com",
        status: false,
    },
    {
        id: "3",
        fullname: "Nguyễn Văn B",
        phone: "0902457867",
        email: "b.nguyen@gmail.com",
        status: false,
    },
]

var user_manager = [
    {
        id: 0,
        employee_name: "Nguyễn Trí Nhân",
        apply_date: "21/03/2021",
        role: "Sinh viên",
        status: true,
        username: "nhanntse140284@fpt.edu.vn",
        fullname: "Nguyễn Trí Nhân",
        address: "Quận 9, Thành Phố Hồ Chí Minh",
        phone: "0123456789",
        email: "nhanntse140284@fpt.edu.vn",
        languages: "",
        school: "Đại học FPT TPHCM",
        about: "",
    },
    {
        id: 1,
        employee_name: "Nguyễn Văn A",
        apply_date: "21/03/2021",
        role: "Sinh viên",
        status: true,
        username: "a.nguyen@bku.edu.vn",
        fullname: "Nguyễn Văn A",
        address: "Quận 1, Thành Phố Hồ Chí Minh",
        phone: "0123456789",
        email: "a.nguyen@bku.edu.vn",
        languages: "Tiếng Anh",
        school: "Đại học Bách Khoa TPHCM",
        about: "",
    },
    {
        id: 2,
        employee_name: "Trần Thị H",
        apply_date: "21/03/2021",
        role: "Sinh viên",
        status: true,
        username: "tranthih@hutech.edu.vn",
        fullname: "Trần Thị H",
        address: "Quận 12, Thành Phố Hồ Chí Minh",
        phone: "0123456789",
        email: "tranthih@hutech.edu.vn",
        languages: "",
        school: "Đại học công nghệ TPHCM",
        about: "",
    }
]


var company = [
    {
        name: "Công ty TNHH Vòng Tròn Đỏ",
        image_link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBtmE5u0HTHkD8cmS9ilCnQ8YgkZDHG7gfLItW_I7LcJ2ImtwMZoAKnyMwTkp4oA16-hE&usqp=CAU",
        email: "info@circlek.com.vn",
        phone: "19003110",
        address: "160 Bùi Thị Xuân, Phường Phạm Ngũ Lão, Quận 1, Tp.HCM"
    }
]

var activities = [
    {
        name: "Công ty TNHH Vòng Tròn Đỏ",
        activity: "Đã đăng bài tuyển dụng",
        date: "10/05/2021",
    },
    {
        name: "Công ty TNHH Vòng Tròn Đỏ",
        activity: "Đã đăng bài tuyển dụng",
        date: "11/05/2021",
    },
    {
        name: "Công ty TNHH Vòng Tròn Đỏ",
        activity: "Đã đăng bài tuyển dụng",
        date: "12/05/2021",
    },
    {
        name: "CÔNG TY CP HÀNG TIÊU DÙNG MASAN",
        activity: "Đã đăng bài tuyển dụng",
        date: "13/05/2021",
    },
    {
        name: "CÔNG TY CP HÀNG TIÊU DÙNG MASAN",
        activity: "Đã đăng bài tuyển dụng",
        date: "13/05/2021",
    },
    {
        name: "CÔNG TY CP HÀNG TIÊU DÙNG MASAN",
        activity: "Đã đăng bài tuyển dụng",
        date: "14/05/2021",
    },
    {
        name: "CÔNG TY CP HÀNG TIÊU DÙNG MASAN",
        activity: "Đã đăng bài tuyển dụng",
        date: "14/05/2021",
    },
    {
        name: "CÔNG TY CP HÀNG TIÊU DÙNG MASAN",
        activity: "Đã đăng bài tuyển dụng",
        date: "20/05/2021",
    },
    {
        name: "CÔNG TY CP HÀNG TIÊU DÙNG MASAN",
        activity: "Đã đăng bài tuyển dụng",
        date: "20/05/2021",
    },
    {
        name: "Nguyễn Trí Nhân",
        activity: "Đã ứng tuyển vị trí Nhân viên bán hàng tại Công ty TNHH Vòng Tròn Đỏ",
        date: "13/05/2021",
    },

]

var report_data = [
    {
        username: "Nguyên Văn A",
        description: "Bài đăng tuyển không rõ ràng",
        job_id: "19",
        reason: "Công ty không ghi đầy đủ địa chỉ văn phòng, gây khó khăn cho việc tìm kiếm",
        date: "13/05/2021"
    },
    {
        username: "Trần Thị H",
        description: "Công ty đăng tuyển không đúng với nội dung thực tế",
        job_id: "21",
        reason: "Công ty đăng tuyển ở gò vấp nhưng lúc hẹn chỗ phỏng vấn lại ở Tân Bình," +
            "có vẻ như công ty đã chuyển văn phòng nhưng chưa cập nhật lại thông tin",
        date: "20/05/2021"
    }
]

var companies_data = [
    {
        id: 0,
        company_name: "The coffee house",
        image_link: "https://rubee.com.vn/admin/webroot/upload/image/images/tin-tuc/the-coffee-house-logo-2.jpg",
        company_address: "quận Tân Bình, thành phố Hồ Chí Minh",
        date_create: "10/06/2021",
        status: true,
        email: "hi@thecoffeehouse.vn",
        phone: "02871078079",
        address: "88 Cao Thắng, Phường 4, Quận 3, Tp.HCM"
    },
    {
        id: 1,
        company_name: "CÔNG TY CP HÀNG TIÊU DÙNG MASAN",
        image_link: "https://cdn.brvn.vn/news/480px/2013/masanhuydongvon0_1373616909.jpg",
        company_address: " MPlaza, 39 Lê Duẩn, Bến Nghé, Quận 1, Hồ Chí Minh",
        date_create: "01/06/2021",
        status: true,
        email: "info@masan.com.vn",
        phone: "19007911",
        address: "MPlaza, 39 Lê Duẩn, Bến Nghé, Quận 1, Hồ Chí Minh"
    },
    {
        id: 2,
        company_name: "Công Ty Tnhh A.N Sài Gòn Group",
        image_link: "https://cdn1.timviecnhanh.com/images/default/2021/06/18/images/162400169835.jpeg",
        company_address: "Số 85 Đường Số 6, Ấp Tiền Lân, Xã Bà Điểm, Huyện Hóc Môn, Thành phố Hồ Chí Minh",
        date_create: "18/06/2021",
        status: true,
        email: "about@saigoncoop.com.vn",
        phone: "19006564",
        address: "Số 85 Đường Số 6, Ấp Tiền Lân, Xã Bà Điểm, Huyện Hóc Môn, Thành phố Hồ Chí Minh"
    },
    {
        id: 3,
        company_name: "CÔNG TY CP PIZZA NGON",
        image_link: "https://cdn1.timviecnhanh.com/asset/home/img/employer/5aa88868f0846_1520994408.png",
        company_address: "Tòa nhà Lottery Tower - Lầu 10, 77 Trần Nhân Tôn, Phường 9, Quận 5, HCM",
        date_create: "19/06/2021",
        status: true,
        email: "pizza.ngon@gmail.com",
        phone: "19007272",
        address: "Tòa nhà Lottery Tower - Lầu 10, 77 Trần Nhân Tôn, Phường 9, Quận 5, HCM"
    },
    {
        id: 4,
        company_name: "TT Trực Tuyến Workonline 24H",
        image_link: "https://cdn1.timviecnhanh.com/asset/home/img/employer/5ebcabed03b02_1589423085.jpg",
        company_address: "Quận 3, thành phố Hồ Chí Minh",
        date_create: "19/06/2021",
        status: true,
        email: "trinhtran.manager@gmail.com",
        phone: "0127898264",
        address: "Quận 3, thành phố Hồ Chí Minh"
    },
    {
        id: 5,
        company_name: "Công Ty Tnhh Ministop Việt Nam",
        image_link: "https://cdn1.timviecnhanh.com/images/default/2021/06/18/images/162400169835.jpeg",
        company_address: "Số 85 Đường Số 6, Ấp Tiền Lân, Xã Bà Điểm, Huyện Hóc Môn, Thành phố Hồ Chí Minh",
        date_create: "20/06/2021",
        status: true,
        email: "hi@ministop.com",
        phone: "19004546",
        address: "Số 85 Đường Số 6, Ấp Tiền Lân, Xã Bà Điểm, Huyện Hóc Môn, Thành phố Hồ Chí Minh"
    },
    {
        id: 6,
        company_name: "Siêu Thị Big C",
        image_link: "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/18158268c55b328c797f859b5fc9add6.png",
        company_address: "Hồ Chí Minh, Thành phố Hồ Chí Minh",
        date_create: "20/06/2021",
        status: true,
        email: "info@bigc.com",
        phone: "19001864",
        address: "Hồ Chí Minh, Thành phố Hồ Chí Minh"
    },
    {
        id: 7,
        company_name: "Cafe tại Hồ Chí Minh",
        image_link: "https://thumbs.dreamstime.com/b/homemade-dark-chocolate-biscotti-cookies-almonds-covered-melted-chocolate-cup-coffee-square-format-homemade-dark-101903597.jpg",
        company_address: "Quận 4, thành phố Hồ Chí Minh",
        date_create: "20/06/2021",
        status: true,
        email: "antran1212@gmail.com",
        phone: "0962888475",
        address: "Quận 4, thành phố Hồ Chí Minh"
    },

]

// import vào, đặt const rồi gọi thôi

module.exports = {
    data_manage_hr_page: data_manage_hr_page,
    data_home_page: data_home_page,
    loremipsum: loremipsum,
    hr_user: hr_user,
    student_user: student_user,
    employees,
    company: company,
    user: user_manager,
    activities,
    report_data,
    companies_data,
};
